services:
  metabase:
    image: metabase/metabase:v0.58.4.x
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    #environment:
      #MB_DB_TYPE: postgres
      #MB_DB_DBNAME: ${POSTGRES_METABASE_DBNAME}
      #MB_DB_PORT: ${POSTGRES_METABASE_PORT}
      #MB_DB_USER: ${POSTGRES_METABASE_USERNAME}
      #MB_DB_PASS: ${POSTGRES_METABASE_PASSWORD}
      #MB_DB_HOST: postgres-dwh
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
